services:
  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    volumes:
      - minio_db:/data
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin # Change to a secure user in production
      MINIO_ROOT_PASSWORD: minioadmin # Change to a secure password
    command: server /data --console-address ":9001"

  postgres:
    image: kartoza/postgis:17-3.5
    container_name: postgis
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - pg_db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=mappy_db
      - POSTGRES_USER=mappyadmin
      - POSTGRES_PASS=mappypassword
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting

  pgadmin:
    image: dpage/pgadmin4:9.3.0
    container_name: my_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - pg4_db:/var/lib/pgadmin

  mappy:
    image: ewadus/mappy:1.0.0
    container_name: mappy
    restart: always
    depends_on:
      - postgres
      - pgadmin
      - minio
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://mappyadmin:mappypassword@postgres:5432/mappy_db
      - MINIO_PROTOCAL=http
      - MINIO_ENPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKETNAME=mappy
      - MINIO_PUBLIC_URL=http://minio:9000

volumes:
  pg_db:
  pg4_db:
  minio_db:
